[package]
# Test case 3: Unsorted with existing [package] section

[dependencies]
anyhow = "1.0"
chrono = { features = ["serde"], version = "0.4" }
uuid = "1.0"

[dev-dependencies]
proptest = "1.0"
tempfile = "3.0"

[features]
default = []
serde = ["chrono/serde"]
