[package]
# Author information
authors = ["Developer"]
edition = "2021"
name = "commented-project"
# Test case 4: Unsorted with comments throughout
# This is a test project
version = "0.3.0"

[dependencies]
# Serialization
serde = { features = ["derive"], version = "1.0" }
# JSON handling
serde_json = "1.0"
# Async runtime
tokio = { features = ["full"], version = "1.0" }
# Web framework
warp = "0.3"

[dev-dependencies]
# Testing framework
criterion = "0.5"
# HTTP client for tests
reqwest = "0.11"
