# Test case 1: Basic unsorted Cargo.toml with top-level package info
version = "0.1.0"
name = "test-project"
edition = "2021"
authors = ["John Doe <john@example.com>"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = "1.0"
clap = "4.0"

[dev-dependencies]
criterion = "0.5"
assert_cmd = "2.0"

