# Test case 4: Unsorted with comments throughout
# This is a test project
version = "0.3.0"
name = "commented-project"
# Author information
authors = ["Developer"]
edition = "2021"

[dependencies]
# Web framework
warp = "0.3"
# Serialization
serde = { version = "1.0", features = ["derive"] }
# JSON handling
serde_json = "1.0"
# Async runtime
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
# Testing framework
criterion = "0.5"
# HTTP client for tests
reqwest = "0.11"

