[package]
edition = "2021"
name = "test-project"
# Test file for formatter chaining
version = "0.1.0"

[dependencies]
anyhow = "1.0"
serde_json = "1.0"
tokio = { features = ["rt-multi-thread", "macros"], version = "1.0" }
clap = { features = ["derive"], version = "4.0" }

[dev-dependencies]
criterion = "0.5"
tokio-test = "0.4"

[features]
async = ["tokio"]
default = ["std"]
std = []
